var en = {
  name:'name',
  username:'username',
  login:'login',
  password:'password',
  submit:'login',
  title:'remind',
  msg:'please write the complete information',
  msg1:'administrtor signs in successfully',
  msg2:' ware-houseman signs in successfully',
  msg3:'sign out successfully',
  login_err:'sign in unsuccessfully',
  login_err1:'sign out unsuccessfully',
  ruku:'shipping',
  chuku:'receiving',
  zengku:'Storehouse',
  jianku:'Having Spikelet',
  yiku:'Transfer Library',
  fenxiang:'Binning',
  pandian:'check',
  tuiku:'Cancelling stocks',
  disong:'Delivery',
  dengchu:'Log out',
  renwu:'task',
  wo:'me',
  disong:'delievery',
  scan:'scan',
  changelanguage:'change language',
  delievery:'delievery task',
  status:'status',
  delieverytaskcode:'delievery task code'
}
