
var zh = {
  name:'名字',
  username:'用户名',
  login:'登陆',
  password:'密码',
  submit:'确认',
  title:'提醒',
  msg:'请填写完整的信息',
  msg1:'admin登陆成功',
  msg2:'仓库管理员登陆成功',
  msg3:'登出成功',
  login_err:'登陆失败',
  login_err1:'登出失败',
  ruku:'入库',
  chuku:'出库',
  zengku:'增库',
  jianku:'减库',
  yiku:'移库',
  fenxiang:'分箱',
  pandian:'盘点',
  tuiku:'退库',
  disong:'递送',
  dengchu:'登出',
  renwu:'任务',
  wo:'我',
  disong:'递送',
  scan:'扫码',
  changelanguage:'切换语言',
  delievery:'递送任务',
  status:'状态',
  delieverytaskcode:'递送任务码'
//   //  delieveryin.html 文件;
//   weikaishi:'未开始',
//   zhixingzhong:'执行中',
//   wancheng:'完成',
//   nodata:'暂时无递送任务',
//   //delieveryinwork.html 文件;
//   delieverynumber:'递送单编号',
//   //delieveryincast.html 文件
//   delieveryinfor:'递送单信息',
//   submit:'签收',
//   name:'姓名',
//   city:'城市',
//   street:'街道',
//   address:'具体地址',
//   tel:'电话',
//   nodelieveryinfo:'无订单信息',
//   submitsucc:'签收成功',
//   submitdone:'已签收',
//   choosemap:'选择地图',
//   cancel:'取消',
//   googlemap:'谷歌地图',
//   baidumap:'百度地图',
//   installgooglemap:'请安装谷歌地图',
//   delieverydan:'递送单'
//   addin.html 文件;
//   addintask:'增库任务',
//   addintasknum:'增库任务码',
//   noaddin:'暂时无入库任务',
//   addincast.html 文件;
//   addinshangjia:'增库上架',
//   thingsinfo:'商品信息',
//   pici:'批次',
//   danwei:'单位',
//   currnum:'当前个数',
//   kuwei:'库位',
//   kucuninfo:'库存信息',
//   shangjia:'上架',
//   scanerr:'上架错误',
//   thingname:'商品名',
//   thingupc:'商品UPC',
//   expdate:'有效期',
//   putonnum:'上架个数',
//   caigounum:'采购个数',
//   nolog:'没有此纪录,请检查商品信息码',
//   fullinfo:'请完善相关信息',
//   taskinfo:'请填写库存信息',
//   putonsucc:'上架成功',
//   putonfail:'上架失败',
//   writecode:'请输入库存代码',
//   depotcode:'库存代码',
//   depotname:'库存仓库名字',
//   remark:'备注',
//   nologtask:'没有此纪录,请检查仓库信息码',
//   thingsnum:'商品编号',
//   currtaskinfo:'当前无库存',
//   inputthingcode:'请输入商品代码',
//   //addinwork.html 文件
//   addinlog:'增库记录',
//   start:'开始',
//   del:'删除',
//   finish:'结束',
//   noaddinlog:'暂无入库记录',
//   cannotgetinfo:'无法获取信息',
//   noinfo:'无信息',
//   finifail:'结束失败',
//   //checkin.html 文件;
//   checktask:'盘点任务',
//   checktaskcode:'盘点任务码',
//   nocheckintask:'暂时无盘点任务',
//   delsucc:'删除成功',
//   delfail:'删除失败',
//   finishcheckin:'此盘点任务完成',
//   failcheckin:'未成功结束此盘点任务',
//   writenewnum:'填写新盘点个数',
//   modifysucc:'修改成功',
//   modifyfail:'修改失败',
//   canceldone:'已取消',
//   houselist:'库位列表',
//   modifylist:'修改记录',
//   housedoneinfo:'库位完成信息',
//   dec:'减库下架',
//   decline:'下架',
//   writetaskcode:'请输入库存代码',
//   decnum:'下架个数',
//   decfail:'下架失败'
//   //decinwork.html 文件
//   dectask:'减库任务'，
//   declog:'减库记录',
//   content:'内容',
//   dingdancode:'订单号',
//    //incast.html 文件;
//   putin:'入库上架',
//   caigoucode:'采购单号',
//   //inwork.html 文件;
//   putinlog:'入库记录',
//   caigounum:'采购数',
//   kucuncode:'库存码',
//   //movedecast.html 文件;
//   movetask:'分箱任务',
//   housecode:'库位码',
//   operation:'操作',
//   //movein.html  文件;
//   movetaskcode:'分箱任务码',
//   moveinsucc:'此分箱任务完成',
//   moveinfail:'未成功结束此分箱任务',
//   //moveincast.html  文件;
//   starttime:'创建时间',
//   //outincast.html 文件；
//   sortingbox:'分拣箱',
//   ordernum:'订单编号',
//   sortingboxnum:'分拣箱编码',
//   sortingboxremark:'分拣箱备注',
//   sure:'确定',
//   sortsucc:'分配分拣箱成功',
//   sortfail:'分配分拣箱失败',
//   inputsortcode:'请输入分箱编码',
//   //outincast1.html  文件;
//   sort:'分拣',
//   currsortinginfo:'本次分拣信息',
//   targetbox:'目标分拣箱',
//   sortnum:'分拣数量',
//   ordernum:'订购数量',
//   sortfail:'分拣失败',
//   sortsucc:'分拣成功',
//   //outincast2.html 文件;
//   repose:'复核',
//   noreposeinfo:'无复核信息',
//   //outinwork.html 文件;
//   outgoingtask:'出库任务',
//   member:'会员',
//   thingstype:'商品类型',
//   freezingtype:'冷冻商品',
//   generalthing:'普通商品',
//   sale:'销售价',
//   contentlog:'记录内容',
//   startzongjian:'开始总拣',
//   finishzongjian:'结束总拣',
//   finishfenpei:'分配分拣箱完成',
//   finishfenjian:'分拣完成',
//   finishfuhe:'复核完成',
//   producedelievery:'生成递送单',
//   look:'查看',
//   surepay:'待确认支付',
//   daifahuo:'待发货',
//   daijianhuo:'待拣货',
//   daishouhuo:'待确认收货',
//   daipingjia:'待评价',
//   close:'关闭',
//   clickcancel:'点击取消',
//   //outinwork1.html 文件；
//   failfenjian:'分拣结束失败',
//   //outinwork2.html 文件;
//   fuhenum:'复核数量',
//   finishzongjian:'总拣完成',
//   fuhemsg:'是否复核结束',
//   //outinwork3.html 文件;
//   createdone:'已创建',
//   delieverydone:'已生成递送任务',
//   delieverying:'递送中',
//   signdone:'签收完成',
//   //outinwork4.html 文件;
//   delieverystatus:'递送状态',
// //returnin.html 文件 ;
//   returnin:'退库任务',
//   returnincode:'退库任务码',
//   depot:'退库下架',
//   //shift.html 文件;
//   shift:'移库任务',
//   shiftincode:'移库任务码',
//   //shiftdeccast.html 文件;
//   shiftxiajia:'移库下架',
//   //shiftincast.html 文件;
//   shiftputon:'移库上架',
//   putindate:'入库日期'

}
